name: Frontend CI

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]

concurrency:
  group: frontend-ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    name: Install → Lint → Test (coverage) → Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci
        working-directory: ./frontend

      - name: Lint
        working-directory: ./frontend
        run: |
          if npm run | grep -q "lint"; then
            npm run lint
          else
            echo "No lint script found, skipping."
          fi

      - name: Run tests with coverage
        working-directory: ./frontend
        run: |
          if npm run | grep -q "test:ci"; then
            npm run test:ci
          else
            npx vitest run --coverage
          fi

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          directory: ./frontend/coverage
          flags: frontend
          fail_ci_if_error: true

      - name: Build
        working-directory: ./frontend
        run: |
          if npm run | grep -q "build"; then
            npm run build
          else
            echo "No build script found, skipping."
          fi
