name: Frontend CI

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]

concurrency:
  group: frontend-ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    name: Install → Lint → Test (coverage) → Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Use npm cache (additional)
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      - name: Install dependencies
        run: npm ci

      - name: Lint (permissive for CI)
        run: |
          if npm run | grep -q "lint"; then
            # Ejecuta lint pero no falla el job aunque haya errores
            npm run lint || echo "⚠ ESLint errors ignored for CI"
          else
            echo "No lint script found, skipping."
          fi

      - name: Run tests with coverage
        run: |
          # Preferable: add script "test:ci" in package.json -> "vitest --run --coverage"
          if npm run | grep -q "test:ci"; then
            npm run test:ci
          else
            npx vitest --run --coverage
          fi

      - name: Upload coverage report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: frontend-coverage
          path: ./coverage

      - name: Build
        run: |
          if npm run | grep -q "build"; then
            npm run build
          else
            echo "No build script found, skipping."
          fi
